name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install bump-my-version
        run: |
          uv tool install bump-my-version

      - name: Bump version
        id: bump
        shell: bash
        run: |
          echo "previous-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
  
          bump-my-version bump ${{ inputs.bump-type }}
          ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") >> $GITHUB_OUTPUT
          echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      - name: Update changelog
        id: changelog
        uses: release-flow/keep-a-changelog-action@v2
        with:
          command: bump
          version: ${{ inputs.bump-type }}
          keep-unreleased-section: true
          fail-on-empty-release-notes: true

      - name: Create branch and commit
        id: create_branch
        run: |
          git config --local user.email "open-source@github.com"
          git config --local user.name "DeepL Open-Source Bot"
          git checkout -b bumpversion-${{ steps.bump.outputs.current-version }}
          git add .
          git commit -m "docs: Increase version to ${{ steps.bump.outputs.current-version }}"

      - name: Push changes
        id: push_changes
        run: |
          git push --set-upstream origin bumpversion-${{ steps.bump.outputs.current-version }}
          
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump version to ${{ steps.get_version.outputs.new_version }}"
          body: "This PR bumps the version to ${{ steps.get_version.outputs.new_version }} and updates the changelog."
          head: bumpversion-${{ steps.get_version.outputs.new_version }}
          base: main
