name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        with:
          args: ${{ inputs.bump-type }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Update changelog
        id: changelog
        uses: release-flow/keep-a-changelog-action@v2
        with:
          command: bump
          version: ${{ inputs.bump-type }}
          keep-unreleased-section: true
          fail-on-empty-release-notes: true

      - name: Create branch and commit
        id: create_branch
        run: |
          git config --local user.email "open-source@github.com"
          git config --local user.name "DeepL Open-Source Bot"
          git checkout -b bumpversion-${{ steps.bump.outputs.current-version }}
          git add .
          git commit -m "docs: Increase version to ${{ steps.bump.outputs.current-version }}"
          git push origin bumpversion-${{ steps.bump.outputs.current-version }}
          
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump version to ${{ steps.get_version.outputs.new_version }}"
          body: "This PR bumps the version to ${{ steps.get_version.outputs.new_version }} and updates the changelog."
          head: bumpversion-${{ steps.get_version.outputs.new_version }}
          base: main
